/**
 * copy.js — SynerArch 全站唯一文案来源
 * 
 * 使用方法：
 *   修改此文件中的文案后，刷新页面即可看到更新。
 *   EN = 英文，JP = 日文
 *   每个 key 对应页面中的一处文案。
 * 
 * 文件结构：
 *   COPY.global   — 导航、页脚等全站共用文案
 *   COPY.index    — 首页
 *   COPY.ai       — AI / Platform 页
 *   COPY.about    — About 页
 *   COPY.contact  — Contact 页
 *   COPY.demo     — Request Demo 页
 *   COPY.solutions.energy        — Energy Optimization 解决方案页
 *   COPY.solutions.construction  — Construction Decarbonization 解决方案页
 *   COPY.solutions.compliance    — Carbon Compliance & LCA 解决方案页
 *   COPY.solutions.retrofit      — Circular Retrofit 解决方案页
 *   COPY.solutions.materials     — Materials & Circular Supply 解决方案页
 */

const COPY = {
  global: {
    en: {
      "nav-solutions": `Solutions`,
      "nav-platform": `Methods`,
      "nav-about": `About`,
      "nav-contact": `Contact`,
      "nav-demo": `Request Demo`,
      "nav-databank": `Data Bank`,
      "footer-head-use": `Use Cases`,
      "footer-head-comp": `Company`,
      "footer-priv": `Privacy Policy`,
      "footer-terms": `Terms`,
      "sol-energy-title": `Energy Optimization`,
      "sol-mat-title": `Low-carbon material`,
      "sol-retrofit-title": `Circular Renovation & Asset Optimization`,
      "sol-const-title": `Construction Decarbonization`,
      "sol-carbon-title": `LCA Compliance`,
    },
    jp: {
      "nav-solutions": `ソリューション`,
      "nav-platform": `Methods`,
      "nav-about": `会社情報`,
      "nav-contact": `お問い合わせ`,
      "nav-demo": `デモを依頼`,
      "nav-databank": `データバンク`,
      "footer-head-use": `ユースケース`,
      "footer-head-comp": `会社情報`,
      "footer-priv": `プライバシーポリシー`,
      "footer-terms": `利用規約`,
      "sol-energy-title": `エネルギー最適化`,
      "sol-mat-title": `材料・循環供給`,
      "sol-retrofit-title": `サーキュラー改修`,
      "sol-const-title": `施工カーボン管理`,
      "sol-carbon-title": `LCAコンプライアンス`,
    },
  },

  index: {
    en: {
      "hero-title": `Architecting your building data foundation`,
      "hero-desc": `Integrate BIM, BMS, energy, and material data across your portfolio into a unified, structured layer — making your building data computable, auditable, and continuously valuable, in alignment with compliance disclosure and carbon management requirements.`,
      "hero-input-placeholder": `Ask SynerArch`,
      "hero-explore": `Data Bank`,
      "hero-sub": `An AI-native data foundation for the building lifecycle—to make performance computable, auditable, and continuously valuable.`,
    "stat-deployments": `Live Deployments`,
    "stat-cities": `Cities`,
    "stat-sqm": `sq m Managed`,
    "stat-data": `Building Data`,
    "apollo-banner": `The built environment is entering its Apollo moment — the most effective way to manage atoms is to first manage the bits that describe them. That data infrastructure layer is still missing. We are building it.`,
      "hero-trust": `Supports multi-building portfolios (10–1000+ assets) · Data coverage up to 90% · Audit-ready outputs`,
      "agent-status": `Secure environment for enterprise data integration`,
      "sol-title": `Intelligence across your building lifecycle`,
      "sol-subtitle": `From materials procurement and construction management to building operations, retrofit, and carbon compliance — integrating BIM and operational data to unify every critical node across the building lifecycle, in alignment with compliance disclosure and carbon management requirements.`,
      "sol-energy-desc": `Energy savings — continuous monitoring, issue detection, proactive optimization... Lower operating costs — energy-saving retrofit strategies, effective building equipment management... Smarter decisions — data-driven insights, optimal decision-making, predictive intelligence`,
      "sol-mat-desc": `Promotion — supply-chain efficiency matching, R&D support... Low-carbon Data House — EPD data, supplier information, on-site photos... Construction Waste Recycling — cradle to cradle strategy, recycle market fit...`,
      "sol-retrofit-desc": `Sustainability Strategies — improve transparency across LCA scores, circularity indices, resource consumption metrics... Circular retrofit & Lifecycle Management — driving the circular economy, maximizing asset reuse rates... Building Deconstruction Inventory — empowering material recovery operators, accelerating regional resource circularity...`,
      "sol-const-desc": `Track and manage on-site construction emissions — aligned with ISO 14064, PAS 2080, EPA Tier 4, Off-Road Act... MRV-ready data collection — efficient capture via IoT, OCR, mobile tools... Construction equipment energy monitoring — clean energy alternatives, scheduling optimization...`,
      "sol-carbon-desc": `Regulatory & Standards compliance — alignment with global frameworks: ISO 14040/44, ISO 14064, ESRS, TCFD, LEED, BREEAM, ZEB, J-Credit, Carbon Credit. Accelerated Green Financing — transparent, data-driven decision bases for financial institutions and project stakeholders. Maximizing Asset Appreciation — transforming full lifecycle building data into computable, auditable and continuously appreciating assets.`,
      "flow-1": `Materials`,
      "flow-1-tip": `Leverage EPD data, supplier information, and inventory data to improve decision-making for low-carbon material design and procurement.`,
      "flow-2": `Construction`,
      "flow-2-tip": `Use mobile tools to record site energy use, material consumption, and equipment activity — continuously improving data visibility and reporting accuracy throughout the construction phase.`,
      "flow-3": `Operations`,
      "flow-3-tip": `Continuously monitor building operations with AI, detect issues, and proactively optimize performance to reduce energy consumption.`,
      "flow-4": `Urban Mining`,
      "flow-4-tip": `Identify reusable assets and classify materials based on optimal retrofit or deconstruction scenarios, reducing construction waste.`,
      "flow-5": `Compliance`,
      "flow-5-tip": `Consolidate lifecycle carbon data across projects and portfolios, generate standardized reports, and transform building data into carbon assets.`,
      "data-title": `Turn building data into asset intelligence`,
      "data-subtitle": `AI integrates and structures BIM and building data of all types, building standardized data models. Combined with industry rules and validation logic, it continuously generates specialized databases for energy optimization, carbon accounting, and lifecycle analysis — providing an always-available data foundation across the full building lifecycle.`,
      "arch-core-title": `AI Data Core — BIM Integrated`,
      "arch-core-desc": `Integrates BIM models, IoT data, and operational data from every lifecycle stage into a structured data layer. Continuously learns from multi-source building data to build standardized data models, supporting lifecycle-wide analysis, anomaly detection, and optimization.`,
      "arch-out-1-title": `Modeling`,
      "arch-out-1-desc": `Avoid "rubbish in, rubbish out" — standardised data structured through a building industry domain view.`,
      "arch-out-2-title": `Rules`,
      "arch-out-2-desc": `Automated validation and calculation, combined with industry rules and policy logic, to continuously generate the rule sets required for compliance.`,
      "arch-out-3-title": `Methodology`,
      "arch-out-3-desc": `A directly callable function for energy optimisation, carbon accounting, lifecycle analysis, and more.`,
      "partners-title": `Trusted by leading organizations`,
      "cta-title": `See how our solutions work for your buildings`,
      "cta-desc": `Request a detailed walkthrough covering energy optimization, carbon asset compliance, and lifecycle data management — maximizing the value of your building data and transforming it into continuously appreciating carbon assets.`,
      "cta-contact": `Contact Us`,
      "out-1-label": `Energy`,
      "out-1-val": `↓ 20–30%`,
      "out-2-label": `Carbon`,
      "out-2-val": `↓ 15–25%`,
      "out-3-label": `Operational Cost`,
      "out-3-val": `↓ 10–20%`,
      "out-4-label": `Data Coverage`,
      "out-4-val": `60–90% Improvement`,
      "out-1-label-full": `Energy reduction: 20–30%`,
      "out-2-label-full": `Carbon reduction: 15–25%`,
      "out-3-label-full": `Operational cost reduction: 10–20%`,
      "out-4-label-full": `Data coverage improvement: 60–90%`,
      "footer-desc": `AI-powered solutions for BIM-enabled buildings, carbon, and lifecycle management.`,
    },
    jp: {
      "hero-title": `建物データ基盤を、ともに設計する`,
      "hero-desc": `資産ポートフォリオ全体のBIM・BMS・エネルギー・材料データを統合・構造化し、一元管理する基盤を提供します。建物データを演算可能で監査に耐え、継続的に価値を高める資産へと変え、各種コンプライアンス開示およびカーボンマネジメント要件に対応します。`,
      "hero-input-placeholder": `SynerArchに質問する`,
      "hero-explore": `データバンク`,
      "hero-sub": `建物ライフサイクルのためのAIネイティブデータ基盤——性能をコンピュータブル、監査可能、継続的に価値あるものにするために。`,
    "stat-deployments": `実稼働プロジェクト`,
    "stat-cities": `対象都市`,
    "stat-sqm": `㎡ 管理面積`,
    "stat-data": `構造化建築データ`,
    "apollo-banner": `建築業界は、その「アポロの瞬間」を迎えようとしています——物理的な建物を管理する最も効果的な方法は、まずそれを記述するデジタル情報を管理することです。そのデータ基盤は、いまだ存在しない。私たちがそれを構築します。`,
      "hero-trust": `複数建物対応（10〜1000棟）・データ可視化最大90%・監査対応`,
      "agent-status": `エンタープライズデータ接続環境`,
      "sol-title": `建物ライフサイクル全体のインテリジェンス`,
      "sol-subtitle": `材料調達・施工管理から建物運用・改修・カーボンコンプライアンスまで、BIMおよび各種運用データを統合し、建物ライフサイクル全体の重要ノードを一元管理。各種コンプライアンス開示およびカーボンマネジメント要件にシームレスに対応します。`,
      "sol-energy-desc": `AIによるエネルギー最適化で建物の運用効率を向上させます。HVAC・空間・照明・設備負荷を継続的に監視し、問題を検知してプロアクティブに最適化。エネルギー消費を20〜30%削減します。`,
      "sol-mat-desc": `低炭素材料と再利用可能な構成部材を探索します。EPDデータセット・サプライヤー情報・在庫データを活用し、設計および調達の意思決定の効率を向上。隠れたカーボン排出を10〜25%削減することに貢献します。`,
      "sol-retrofit-desc": `ライフサイクルおよびマテリアルリカバリーデータをもとに意思決定を行います。循環型戦略を活用し、最適な改修・解体シナリオを立案・実行。再利用可能な資産を特定し材料を分類することで、建設廃棄物を30〜50%削減します。`,
      "sol-const-desc": `施工フェーズ全体のエネルギー消費とカーボン排出を追跡・管理します。現場のエネルギー使用量・材料消費・設備稼働を記録し、コンプライアンス開示およびカーボンマネジメント要件に対応したデータ収集フローを支援。データの可視化とレポート精度（±5〜10%）を継続的に向上させます。`,
      "sol-carbon-desc": `プロジェクトおよびポートフォリオ全体のライフサイクルカーボンデータを統合し、標準化されたレポートを生成します。Scope 1–3の算定、LCA評価、MRVおよび各種コンプライアンス開示・カーボンマネジメント要件に対応し、建物データを演算可能で監査に耐え、継続的に価値を高めるカーボン資産へと転換。データ価値を最大化します。`,
      "flow-1": `材料`,
      "flow-1-tip": `EPDデータ・サプライヤー情報・在庫データを活用し、低炭素材料の設計・調達における意思決定の効率を向上させます。`,
      "flow-2": `施工`,
      "flow-2-tip": `モバイルツールを活用して現場のエネルギー使用量・材料消費・設備稼働を記録し、施工フェーズ全体のデータ可視化とレポート精度を継続的に向上させます。`,
      "flow-3": `運用`,
      "flow-3-tip": `AIによる継続的な建物の稼働状況の監視、問題の検知、プロアクティブな最適化により、エネルギー消費を削減します。`,
      "flow-4": `アーバンマイニング`,
      "flow-4-tip": `最適な改修・解体シナリオに基づき、再利用可能な資産を特定し材料を分類。建設廃棄物を削減します。`,
      "flow-5": `コンプライアンス`,
      "flow-5-tip": `プロジェクトおよびポートフォリオ全体のライフサイクルカーボンデータを統合し、標準化レポートを生成。建物データをカーボン資産へと転換します。`,
      "data-title": `建物データを資産インテリジェンスへ`,
      "data-subtitle": `AIがBIMおよびあらゆる種類の建物データを統合・構造化し、標準化されたデータモデルを構築します。業界ルールと検証ロジックを組み合わせることで、エネルギー最適化・カーボン算定・ライフサイクル分析のための専門データベースを継続的に生成し、建物ライフサイクル全体で即時参照可能なデータ基盤を提供します。`,
      "arch-core-title": `BIM統合AIデータコア`,
      "arch-core-desc": `BIMモデル・IoTデータ・各フェーズの運用データを構造化データレイヤーへと統合します。複数ソースの建物データから継続的に学習し標準化データモデルを構築。ライフサイクル全体の分析・異常検知・最適化を支援します。`,
      "arch-out-1-title": `モデリング`,
      "arch-out-1-desc": `「ゴミを入れればゴミが出る」を回避 — 建築業界のドメイン視点から構造化された標準化データ。`,
      "arch-out-2-title": `Rules`,
      "arch-out-2-desc": `自動化された検証・計算に業界ルールと政策ロジックを組み合わせ、コンプライアンス要件に必要なルールセットを継続的に生成します。`,
      "arch-out-3-title": `方法論`,
      "arch-out-3-desc": `エネルギー最適化・カーボン算定・ライフサイクル分析などに即時参照可能な関数基盤。`,
      "partners-title": `主要な企業に利用されています`,
      "cta-title": `貴社の建物に当社ソリューションがどう機能するかをご確認ください`,
      "cta-desc": `エネルギー最適化・カーボン資産コンプライアンス・ライフサイクルデータ管理を網羅した詳細デモをご依頼ください。建物データの価値を最大化し、継続的に価値を高めるカーボン資産へと転換します。`,
      "cta-contact": `お問い合わせ`,
      "out-1-label": `エネルギー削減`,
      "out-1-val": `20–30%`,
      "out-2-label": `カーボン削減`,
      "out-2-val": `15–25%`,
      "out-3-label": `運用コスト削減`,
      "out-3-val": `10–20%`,
      "out-4-label": `データ可視化率`,
      "out-4-val": `60–90% 向上`,
      "out-1-label-full": `エネルギー削減：20–30%`,
      "out-2-label-full": `カーボン削減：15–25%`,
      "out-3-label-full": `運用コスト削減：10–20%`,
      "out-4-label-full": `データ可視化率向上：60–90%`,
      "footer-desc": `BIMを活用した建物・カーボン・ライフサイクル管理のためのAIソリューション。`,
    },
  },

  ai: {
    en: {
      "hero-title": `Integrate and structure BIM and all building data, establishing standardized data models that continuously drive analysis and optimization across the full building lifecycle.`,
    "ai-eyebrow": `Not AI layered onto existing software — rebuilt from the data up.`,
      "hero-desc": `Integrate BIM models, BMS, IoT, material, and operational data from every lifecycle stage into standardized, interoperable data structures. Combined with industry rules and validation logic, continuously generate specialized databases for energy optimization, carbon accounting, and lifecycle analysis — reducing data integration costs by 30–50% and improving decision-making efficiency by 20–40%.`,
      "cap-1-title": `Data Integration`,
      "cap-1-tagline": `Immediate ROI · >90% Data Interoperability`,
      "cap-1-desc": `Through standardized data models and data pipelines, integrate BIM, building systems, materials, construction, retrofit, and operational data from every lifecycle stage — achieving over 90% data interoperability and establishing a unified, continuously updated building data foundation.`,
      "cap-1-f1": `BIM, BMS, IoT and asset data unification`,
      "cap-1-f2": `Standardized schemas and data pipelines`,
      "cap-1-f3": `Auditable, continuously updated data foundation`,
      "cap-2-title": `AI Analysis & Modeling`,
      "cap-2-tagline": `Predictive Modeling · Continuous Learning`,
      "cap-2-desc": `Based on AI standardized models and specialized databases — including optimization libraries, rule sets, methodology parameter libraries, and circular strategy libraries — continuously analyze building lifecycle data, identify anomalies, discover optimization opportunities, and continuously improve model precision through iterative learning.`,
      "cap-2-f1": `AI models trained on real building deployments`,
      "cap-2-f2": `Anomaly detection and performance optimization`,
      "cap-2-f3": `Each building connected improves model accuracy network-wide`,
      "cap-3-title": `Generate Actionable Data`,
      "cap-3-tagline": `30–60% Faster Reporting · Decision-ready Outputs`,
      "cap-3-desc": `Continuously generate specialized databases for energy optimization, carbon accounting, and lifecycle analysis, providing a directly callable data foundation for all solutions and improving data visualization and report generation efficiency by 30–60%.`,
      "cap-3-f1": `Energy, carbon, and compliance intelligence`,
      "cap-3-f2": `Lifecycle asset data and digital twin support`,
      "cap-3-f3": `Green finance and MRV-ready data layer`,
      "arch-1-1": `Materials`,
      "arch-1-2": `Construction`,
      "arch-1-3": `Operations`,
      "arch-1-4": `Urban Mining`,
      "arch-1-5": `Compliance`,
      "arch-2-title": `AI Data Core — BIM Integrated`,
      "arch-2-list": `Integrates BIM models, IoT data, and operational data from every lifecycle stage into a structured data layer. Continuously learns from multi-source building data to build standardized data models, supporting lifecycle-wide analysis, anomaly detection, and optimization.`,
      "arch-3-1-t": `Data Models`,
      "arch-3-1-d": `Standardized data structures aligned with compliance disclosure and carbon management requirements`,
      "arch-3-2-t": `Rules`,
      "arch-3-2-d": `Automated validation and calculation combined with industry rules and policy logic to continuously generate required rule sets`,
      "arch-3-3-t": `Insights`,
      "arch-3-3-d": `A directly callable data foundation for energy optimization, carbon accounting, and lifecycle analysis`,
    },
    jp: {
      "hero-title": `BIMおよびあらゆる建物データを統合・構造化し、標準化されたデータモデルを構築。建物ライフサイクル全体の分析と最適化を継続的に推進します。`,
      "ai-eyebrow": `既存ソフトウェアにAIを重ねるのではなく——データの底層から再構築する。`,
      "hero-desc": `BIMモデル・BMS・IoT・材料・各フェーズの運用データを標準化・相互運用可能なデータ構造へ統合。業界ルールと検証ロジックを組み合わせ、エネルギー最適化・カーボン算定・ライフサイクル分析のための専門データベースを継続的に生成します。データ統合コストを30〜50%削減し、意思決定効率を20〜40%向上させます。`,
      "cap-1-title": `データ統合`,
      "cap-1-tagline": `即時ROI · 90%以上のデータ相互運用性`,
      "cap-1-desc": `標準化されたデータモデルとデータパイプラインにより、BIM・建物システム・材料・施工・改修・各フェーズの運用データを統合。90%以上のデータ相互運用性を実現し、統一された継続的に更新可能な建物データ基盤を構築します。`,
      "cap-1-f1": `BIM・BMS・IoT・資産データの統合`,
      "cap-1-f2": `標準化スキーマとデータパイプライン`,
      "cap-1-f3": `監査可能な、継続更新されるデータ基盤`,
      "cap-2-title": `AI分析・モデリング`,
      "cap-2-tagline": `予測モデリング · 継続的学習`,
      "cap-2-desc": `AI標準化モデルおよび最適化ライブラリ・ルールセット・方法学パラメーターライブラリ・循環型戦略ライブラリを含む各種専門データベースに基づき、建物ライフサイクル全体のデータを継続的に分析。異常を検知し、最適化の余地を発見。反復学習によりモデル精度を継続的に向上させます。`,
      "cap-2-f1": `実際の建物展開で訓練されたAIモデル`,
      "cap-2-f2": `異常検知と性能最適化`,
      "cap-2-f3": `接続建物が増えるほどネットワーク全体の精度が向上`,
      "cap-3-title": `活用可能なデータの生成`,
      "cap-3-tagline": `レポート生成30〜60%効率化 · 即活用可能なアウトプット`,
      "cap-3-desc": `エネルギー最適化・カーボン算定・ライフサイクル分析のための専門データベースを継続的に生成。全ソリューションに即時参照可能なデータ基盤を提供し、データ可視化とレポート生成効率を30〜60%向上させます。`,
      "cap-3-f1": `エネルギー・カーボン・コンプライアンス・インテリジェンス`,
      "cap-3-f2": `ライフサイクル資産データとデジタルツイン対応`,
      "cap-3-f3": `グリーンファイナンス・MRV対応データ基盤`,
      "arch-1-1": `材料`,
      "arch-1-2": `施工`,
      "arch-1-3": `運用`,
      "arch-1-4": `アーバンマイニング`,
      "arch-1-5": `コンプライアンス`,
      "arch-2-title": `AIデータコア`,
      "arch-2-list": `複数データソースを統合し、履歴データとリアルタイムデータから学習し、フィードバックループにより継続的にモデルを改善`,
      "arch-3-1-t": `データモデル`,
      "arch-3-1-d": `標準データ構造への変換`,
      "arch-3-2-t": `ルール`,
      "arch-3-2-d": `自動計算・検証`,
      "arch-3-3-t": `インサイト`,
      "arch-3-3-d": `意思決定を支援`,
    },
  },

  about: {
    en: {
      "about-hero-title": `We are building AI-native data infrastructure for the full building lifecycle — transforming fragmented building data into computable, auditable, and continuously appreciating assets.`,
      "about-hero-desc": `Built on 20+ years of architecture and BIM expertise combined with an AI-native data architecture, we deliver solutions for energy optimization, carbon asset management, and lifecycle data management. Starting from Asia-Pacific, we are building the data foundation for the global built environment.`,
      "about-wwd-label": `What We Do`,
      "about-wwd-p1": `The building industry is shifting from delivery-oriented to performance-oriented — yet building data remains fragmented across contractors, consultants, and operators, non-computable and non-auditable. Our work is to change this. Through AI, we integrate and structure BIM and all building data, establishing standardized data models that continuously generate specialized databases for energy optimization, carbon accounting, and lifecycle analysis — providing a directly callable data foundation for building asset operations and decision-making.`,
      "about-wwd-p2": `Our five solutions span the full building lifecycle — low-carbon materials, construction decarbonization, building operations, circular retrofit and deconstruction, and carbon asset compliance — delivering scalable, data-driven tools to developers, asset managers, contractors, and operators, transforming building data into continuously appreciating carbon assets and maximizing data value.`,
    "about-tagline": `Energy is the entry point. Data infrastructure is the business.`,
    },
    jp: {
      "about-hero-title": `私たちは建物ライフサイクル全体のためのAIネイティブなデータインフラを構築しています。断片化された建物データを、演算可能で監査に耐え、継続的に価値を高める資産へと転換します。`,
      "about-hero-desc": `20年以上の建築・BIM分野の深い知見とAIネイティブなデータアーキテクチャを融合し、エネルギー最適化・カーボン資産管理・ライフサイクルデータ管理のソリューションを提供します。アジア太平洋を起点に、グローバルな建成環境のデータ基盤を構築しています。`,
      "about-wwd-label": `事業内容`,
      "about-wwd-p1": `建築業界は「納品志向」から「性能志向」へと移行しています。しかし建物データは依然として、承包業者・コンサルタント・運営者の間で断片化されており、演算も監査もできない状態にあります。私たちはこの現状を変えることを使命としています。AIによってBIMおよびあらゆる建物データを統合・構造化し、標準化されたデータモデルを構築。エネルギー最適化・カーボン算定・ライフサイクル分析等のための専門データベースを継続的に生成し、建物資産の運用と意思決定のための即時参照可能なデータ基盤を提供します。`,
      "about-wwd-p2": `私たちの5つのソリューションは建物ライフサイクル全体をカバーします。低炭素材料・施工脱炭素化・建物運用・循環型改修・解体・カーボン資産コンプライアンスにわたり、デベロッパー・資産管理者・施工業者・運用者に対してスケーラブルなデータ駆動型ツールを提供。建物データを継続的に価値を高めるカーボン資産へと転換し、データ価値を最大化します。`,
      "about-tagline": `エネルギーは入口。データ基盤が、事業の本質。`,
    },
  },

  contact: {
    en: {
      "hero-title": `Get in Touch`,
      "hero-desc": `Whether you are exploring a collaboration, looking to learn more about our technology and solutions, or simply want to connect — we welcome the conversation. We also look forward to building relationships with exceptional talent and media partners in the built environment.`,
      "form-hint": `We recommend briefly describing your project background, including building type, scale, and key objectives (e.g., energy optimization, carbon compliance, retrofit planning), so we can prepare in advance. Our team typically responds within 1–2 business days.`,
      "form-name": `Name`,
      "form-email": `Email`,
      "form-company": `Company`,
      "form-message": `Message`,
      "form-submit": `Send Message`,
      "careers-title": `Join Our Team`,
      "careers-desc": `We are building a team that spans architecture, BIM, data platforms, and AI. If you are passionate about the digitization and decarbonization of the built environment, we welcome you to join us in building the data infrastructure for this industry.`,
      "media-title": `Media & Press`,
      "media-desc": `For press inquiries, reporting collaborations, or industry exchange, please reach out. We are happy to share our thinking and practice on the digitization and low-carbon transition of the built environment.`,
    },
    jp: {
      "hero-title": `お問い合わせ`,
      "hero-desc": `ソリューションに関するご相談、技術・製品の詳細についてのお問い合わせ、あるいは単純なご連絡まで、いつでもお気軽にご連絡ください。建成環境分野の優秀な人材やメディアパートナーとのつながりも歓迎しています。`,
      "form-hint": `プロジェクト概要（建物種類・規模・目的など）をご記入ください。通常1〜2営業日以内にご連絡いたします`,
      "form-name": `お名前`,
      "form-email": `メール`,
      "form-company": `会社`,
      "form-message": `メッセージ`,
      "form-submit": `送信`,
      "careers-title": `採用情報`,
      "careers-desc": `建築・BIM・データプラットフォーム・AIにまたがるチームを構築しています。建成環境のデジタル化と脱炭素化に情熱をお持ちの方は、ぜひ私たちとともにこの業界のデータインフラ構築に参加してください。`,
      "media-title": `メディア・取材`,
      "media-desc": `取材・報道連携・業界交流に関するお問い合わせはこちらからどうぞ。建成環境のデジタル化と低炭素転換に関する私たちの考えと実践を喜んでお伝えします。`,
    },
  },

  demo: {
    en: {
      "hero-title": `Request a Demo`,
      "hero-desc-1": `See how our solutions apply to your buildings and projects`,
      "hero-desc-2": `Based on your BIM models, building data, and project information, we identify key pain points and deliver targeted solutions covering energy optimization, carbon asset compliance, and lifecycle data management. Typical onboarding scope covers 1\\u201310 pilot buildings, with scalable deployment across 10\\u20131000+ assets.`,
      "hero-note": `Typical demo includes data integration overview, sample analytics, and reporting workflows (30\\u201345 min session)`,
      "field-name": `Full Name`,
      "field-title": `Title`,
      "title-placeholder": `Select your title`,
      "title-1": `Developer`,
      "title-2": `Asset Manager`,
      "title-3": `Contractor`,
      "title-4": `Consultant`,
      "title-5": `Sustainability Manager`,
      "title-6": `Other`,
      "field-company": `Company`,
      "field-email": `Email`,
      "field-phone": `Phone (optional)`,
      "field-solution": `Select a solution of interest`,
      "opt-placeholder": `Select an option`,
      "opt-1": `Energy Optimization`,
      "opt-2": `Materials \\u0026 Circular Supply`,
      "opt-3": `Circular Retrofit \\u0026 Asset Recovery`,
      "opt-4": `Construction Decarbonization`,
      "opt-5": `Carbon Compliance \\u0026 LCA`,
      "opt-other": `Other`,
      "field-message": `Message (optional)`,
      "btn-submit": `Submit Request`,
      "form-footer-note": `Not sure what to include? Upload your building data via our Data Bank and we will identify the right solutions for you.`,
      "trust-note": `Our team will review your request and respond within 24\\u201348 hours to schedule a tailored demo session`,
      "success-title": `Thank you. Our team will contact you shortly.`,
      "success-desc": `Your request has been received. A specialist will reach out before the demo to understand your building systems and project scope.`,
      "back-home": `Back to Home`,
    },
    jp: {
      "hero-title": `\\u30c7\\u30e2\\u3092\\u4f9d\\u983c`,
      "hero-desc-1": `\\u8cb4\\u793e\\u306e\\u5efa\\u7269\\u3084\\u30d7\\u30ed\\u30b8\\u30a7\\u30af\\u30c8\\u3067\\u306e\\u6d3b\\u7528\\u3092\\u3054\\u78ba\\u8a8d\\u304f\\u3060\\u3055\\u3044`,
      "hero-desc-2": `\\u5b9f\\u969b\\u306e\\u5efa\\u7269\\u30c7\\u30fc\\u30bf\\u3092\\u7528\\u3044\\u3066\\u3001\\u30a8\\u30cd\\u30eb\\u30ae\\u30fc\\u6027\\u80fd\\u30fb\\u30e9\\u30a4\\u30d5\\u30b5\\u30a4\\u30af\\u30eb\\u30ab\\u30fc\\u30dc\\u30f3\\uff08LCA\\uff09\\u30fb\\u6392\\u51fa\\u7ba1\\u7406\\uff08MRV\\uff09\\u3092\\u8a55\\u4fa1\\u3002\\u521d\\u671f\\u5c0e\\u5165\\u306f1\\uff5e10\\u68df\\u306e\\u30d1\\u30a4\\u30ed\\u30c3\\u30c8\\u304b\\u3089\\u958b\\u59cb\\u3057\\u3001\\u6700\\u59271000\\u68df\\u898f\\u6a21\\u307e\\u3067\\u62e1\\u5f35\\u53ef\\u80fd\\u3002`,
      "hero-note": `\\u30c7\\u30e2\\u5185\\u5bb9\\uff1a\\u30c7\\u30fc\\u30bf\\u63a5\\u7d9a\\u30fb\\u5206\\u6790\\u30fb\\u30ec\\u30dd\\u30fc\\u30c8\\uff0830\\uff5e45\\u5206\\uff09`,
      "field-name": `\\u304a\\u540d\\u524d`,
      "field-title": `\\u30bf\\u30a4\\u30c8\\u30eb`,
      "title-placeholder": `\\u30bf\\u30a4\\u30c8\\u30eb\\u3092\\u9078\\u629e`,
      "title-1": `\\u30c7\\u30d9\\u30ed\\u30c3\\u30d1\\u30fc`,
      "title-2": `\\u30a2\\u30bb\\u30c3\\u30c8\\u30de\\u30cd\\u30fc\\u30b8\\u30e3\\u30fc`,
      "title-3": `\\u65bd\\u5de5\\u4f1a\\u793e`,
      "title-4": `\\u30b3\\u30f3\\u30b5\\u30eb\\u30bf\\u30f3\\u30c8`,
      "title-5": `\\u30b5\\u30b9\\u30c6\\u30ca\\u30d3\\u30ea\\u30c6\\u30a3\\u62c5\\u5f53`,
      "title-6": `\\u305d\\u306e\\u4ed6`,
      "field-company": `\\u4f1a\\u793e\\u540d`,
      "field-email": `\\u30e1\\u30fc\\u30eb\\u30a2\\u30c9\\u30ec\\u30b9`,
      "field-phone": `\\u96fb\\u8a71\\u756a\\u53f7\\uff08\\u4efb\\u610f\\uff09`,
      "field-solution": `\\u95a2\\u5fc3\\u306e\\u3042\\u308b\\u30bd\\u30ea\\u30e5\\u30fc\\u30b7\\u30e7\\u30f3\\u3092\\u9078\\u629e`,
      "opt-placeholder": `\\u9078\\u629e\\u3057\\u3066\\u304f\\u3060\\u3055\\u3044`,
      "opt-1": `\\u30a8\\u30cd\\u30eb\\u30ae\\u30fc\\u6700\\u9069\\u5316`,
      "opt-2": `\\u6750\\u6599\\u30fb\\u5faa\\u74b0\\u4f9b\\u7d66`,
      "opt-3": `\\u30b5\\u30fc\\u30ad\\u30e5\\u30e9\\u30fc\\u6539\\u4fee\\u30fb\\u8cc7\\u7523\\u56de\\u53ce`,
      "opt-4": `\\u65bd\\u5de5\\u30ab\\u30fc\\u30dc\\u30f3\\u7ba1\\u7406`,
      "opt-5": `\\u30ab\\u30fc\\u30dc\\u30f3\\u7ba1\\u7406\\u30fbLCA`,
      "opt-other": `\\u305d\\u306e\\u4ed6`,
      "field-message": `\\u30e1\\u30c3\\u30bb\\u30fc\\u30b8\\uff08\\u4efb\\u610f\\uff09`,
      "btn-submit": `\\u9001\\u4fe1`,
      "form-footer-note": `\\u4efb\\u610f\\uff1a\\u5efa\\u7269\\u30bf\\u30a4\\u30d7\\u30fb\\u68df\\u6570\\u30fb\\u65e2\\u5b58\\u30b7\\u30b9\\u30c6\\u30e0\\uff08BMS\\u30fbIoT\\u7b49\\uff09\\u3092\\u3054\\u8a18\\u5165\\u304f\\u3060\\u3055\\u3044\\u3002\\u5bfe\\u8c61\\u898f\\u6a21\\uff1a1\\u4e07\\uff5e100\\u4e07\\u33a1\\u3001\\u5546\\u696d\\u30fb\\u4f4f\\u5b85\\u30fb\\u8907\\u5408\\u65bd\\u8a2d\\u5bfe\\u5fdc\\u3002`,
      "trust-note": `24\\uff5e48\\u6642\\u9593\\u4ee5\\u5185\\u306b\\u62c5\\u5f53\\u8005\\u3088\\u308a\\u3054\\u9023\\u7d61\\u3057\\u3001\\u30c7\\u30e2\\u65e5\\u7a0b\\u3092\\u3054\\u6848\\u5185\\u3057\\u307e\\u3059`,
      "success-title": `\\u3042\\u308a\\u304c\\u3068\\u3046\\u3054\\u3056\\u3044\\u307e\\u3059\\u3002\\u62c5\\u5f53\\u3088\\u308a\\u3054\\u9023\\u7d61\\u3044\\u305f\\u3057\\u307e\\u3059\\u3002`,
      "success-desc": `\\u3054\\u5165\\u529b\\u5185\\u5bb9\\u3092\\u78ba\\u8a8d\\u5f8c\\u3001\\u5efa\\u7269\\u30c7\\u30fc\\u30bf\\u30fb\\u30b7\\u30b9\\u30c6\\u30e0\\u69cb\\u6210\\u30fb\\u30d7\\u30ed\\u30b8\\u30a7\\u30af\\u30c8\\u7bc4\\u56f2\\u3092\\u4e8b\\u524d\\u78ba\\u8a8d\\u306e\\u3046\\u3048\\u30c7\\u30e2\\u3092\\u3054\\u6848\\u5185\\u3057\\u307e\\u3059\\u3002`,
      "back-home": `\\u30db\\u30fc\\u30e0\\u3078\\u623b\\u308b`,
    },
  },

  solutions: {
    // energy
    energy: {
      en: {
        "hero-title": `Optimize energy consumption and operational performance across your buildings with BIM-integrated data, AI monitoring, analysis, and system control`,
        "hero-desc": `Integrate BMS, IoT, and other data sources into a unified building data model, enabling real-time visibility, anomaly detection, and continuous optimization across HVAC, lighting, and equipment systems — reducing energy consumption by 20–30%, peak load by 10–15%, and operational costs by 10–20%.`,
        "cap1-title": `Real-time Monitoring`,
        "cap1-desc": `Monitor building operations via BMS, IoT sensors, and system integrations at sub-hourly frequency, achieving over 95% data coverage and real-time operational visibility.`,
        "cap2-title": `AI Optimization`,
        "cap2-desc": `Optimize HVAC and equipment operations through AI standardized models, monitoring analytics, and rule sets — reducing energy inefficiency and waste.`,
        "cap3-title": `AI Agent & Control`,
        "cap3-desc": `Use AI Agent to query building operational status, trigger optimization scenarios, and support semi-automated or fully automated control workflows across the entire building.`,
        "howto-label": `How it works`,
        "step1-title": `Collect`,
        "step1-desc": `Collect high-frequency operational data from BMS, IoT sensors, and building systems. Through standardized data pipelines and real-time ingestion, enable continuous visibility into equipment performance and energy consumption.`,
        "step2-title": `Analyze`,
        "step2-desc": `Analyze energy consumption and equipment status using AI standardized models, rule sets, and spatial data mapping integrated with BIM. Identify inefficiencies, anomalies, and performance deviations across HVAC, lighting, and equipment systems.`,
        "step3-title": `Optimize`,
        "step3-desc": `Optimize setpoints, operating schedules, and control strategies based on real-time data. Driven by models and rule sets to reduce energy waste and improve operational efficiency.`,
        "step4-title": `Improve`,
        "step4-desc": `Form a closed loop through feedback and continuous iterative optimization, progressively improving building operational performance and achieving sustained energy efficiency and adaptive control.`,
        "cta-title": `See how this solution applies to your buildings`,
        "cta-desc": `Connect your BMS and IoT data and start optimizing energy and carbon performance across your buildings.`,
        "cta-btn": `Request Demo`,
      },
      jp: {
        "hero-title": `BIM統合データ・AI監視・分析・システム制御により、建物全体のエネルギー消費と運用状態を最適化します`,
        "hero-desc": `BMS・IoTなどのデータソースを統合し、統一された建物データモデルを構築。HVAC・照明・設備システム全体でリアルタイム可視化・異常検知・継続的最適化を実現し、エネルギー消費を20〜30%、ピーク負荷を10〜15%、運用コストを10〜20%削減します。`,
        "cap1-title": `リアルタイム監視`,
        "cap1-desc": `BMS・IoTセンサー・システム統合により、1時間未満の頻度で建物の稼働状況を監視。95%以上のデータカバレッジとリアルタイムの運用可視化を実現します。`,
        "cap2-title": `AI最適化`,
        "cap2-desc": `AI標準化モデル・監視分析・ルールセットを活用し、HVACおよび設備の運用を最適化。エネルギーの非効率と無駄を削減します。`,
        "cap3-title": `AIエージェント・制御`,
        "cap3-desc": `AI Agentを活用して建物の稼働状況を照会し、最適化シナリオをトリガー。建物全体の半自動または全自動制御ワークフローを支援します。`,
        "howto-label": `仕組み`,
        "step1-title": `収集`,
        "step1-desc": `BMS・IoTセンサー・各種建物システムから高頻度の運用データを収集。標準化されたデータパイプラインとリアルタイムデータ取り込みにより、設備稼働とエネルギー消費の継続的な可視化を実現します。`,
        "step2-title": `分析`,
        "step2-desc": `AI標準化モデル・ルールセット・BIM統合空間データマッピングを用いてエネルギー消費と設備状態を分析。HVAC・照明・設備システム全体の非効率・異常・性能偏差を特定します。`,
        "step3-title": `最適化`,
        "step3-desc": `リアルタイムデータに基づき、設定値・稼働スケジュール・制御戦略を最適化。モデルとルールセットにより、エネルギー無駄を削減し運用効率を向上させます。`,
        "step4-title": `改善`,
        "step4-desc": `フィードバックと継続的な反復最適化によりクローズドループを形成し、建物の稼働状態を継続的に改善。エネルギー効率の持続的な最適化と適応制御を実現します。`,
        "cta-title": `貴社建物における本ソリューションの活用をご確認ください`,
        "cta-desc": `BMS・IoTデータを接続し、建物全体のエネルギーとカーボン性能の最適化を開始します。`,
        "cta-btn": `デモを依頼`,
      },
    },
    // construction
    construction: {
      en: {
        "hero-title": `Track and optimize energy consumption, material use, and equipment operations across construction sites through mobile structured data capture and standardized carbon emission rule sets`,
        "hero-desc": `Capture material, equipment, and energy data on-site and convert it into auditable carbon records based on emission factor databases. Matched against AI standardized optimization models and compliance rule sets to reduce energy consumption by 10–20% and meet compliance disclosure and carbon management requirements.uracy and reduced reporting time.`,
        "cap1-title": `Field Data Capture`,
        "cap1-desc": `Capture data using mobile tools with photo, OCR, and structured input workflows, supporting recognition of various on-site data sources and achieving over 90% data extraction accuracy.lection.`,
        "cap2-title": `Material & Waste`,
        "cap2-desc": `Track and manage material and waste quantities as well as site entry and exit records across construction phases using standardized material data and structured logging mechanisms.`,
        "cap3-title": `Energy & Emissions`,
        "cap3-desc": `Calculate emissions from fuel, electricity, and equipment activity using standardized emission factors. Matched against AI optimization models and compliance rule sets to reduce energy consumption by 10–20% and meet compliance disclosure and carbon management requirements.`,
        "howto-label": `How it works`,
        "step1-title": `Capture`,
        "step1-desc": `Collect material, equipment activity, and energy data from construction sites through standardized mobile input workflows, ensuring data consistency and traceability throughout the construction process.nputs. Ensure consistent and traceable data collection across construction activities.`,
        "step2-title": `Recognize`,
        "step2-desc": `Recognize and structure collected data using OCR, classification logic, and predefined data schemas, converting unstructured data into standardized, ready-to-use datasets.ed inputs into standardized and usable datasets.`,
        "step3-title": `Record`,
        "step3-desc": `Record structured data in formats that meet compliance disclosure and carbon management requirements, ensuring consistency and traceability to support subsequent optimization and analysis.raceability, and readiness for downstream carbon analysis.`,
        "step4-title": `Optimize`,
        "step4-desc": `Based on recorded structured data, match against AI standardized optimization models and compliance rule sets to reduce energy consumption and meet compliance disclosure and carbon management requirements.ng workflows and improve reporting efficiency.`,
        "cta-title": `See how this solution applies to your construction sites`,
        "cta-desc": `Connect your site data and start tracking energy, materials, and carbon emissions across your construction projects.`,
        "cta-btn": `Request Demo`,
      },
      jp: {
        "hero-title": `モバイル端末による構造化データ収集と標準化カーボン排出ルールセットにより、施工現場のエネルギー消費・材料使用・設備稼働を追跡・最適化します`,
        "hero-desc": `現場で材料・設備・エネルギーデータを収集し、排出係数データベースに基づく監査可能なカーボン記録へ変換。AI標準化最適化モデルとコンプライアンスルールセットと照合することで、エネルギー消費を10〜20%削減し、各種コンプライアンス開示およびカーボンマネジメント要件を満たします。`,
        "cap1-title": `現場データ取得`,
        "cap1-desc": `写真・OCR・構造化入力を備えたモバイルツールでデータを収集。各種現場データソースの認識に対応し、90%以上のデータ抽出精度を実現します。`,
        "cap2-title": `材料・廃棄物`,
        "cap2-desc": `標準化された材料データと記録メカニズムを用いて、施工各フェーズにおける材料・廃棄物の数量および搬出入情報を追跡・管理します。`,
        "cap3-title": `エネルギー・排出`,
        "cap3-desc": `燃料・電力・設備稼働データから標準排出係数を用いて排出量を算定。AI最適化モデルとコンプライアンスルールセットと照合し、エネルギー消費を10〜20%削減。各種コンプライアンス開示およびカーボンマネジメント要件を満たします。`,
        "howto-label": `仕組み`,
        "step1-title": `取得`,
        "step1-desc": `標準化されたモバイル入力フローにより、施工現場の材料・設備稼働・エネルギー使用データを収集。施工全体を通じたデータの一貫性とトレーサビリティを確保します。`,
        "step2-title": `認識`,
        "step2-desc": `OCR・分類ロジック・事前定義データ構造により収集データを認識・構造化。非構造化データを標準化された利用可能なデータセットへ変換します。`,
        "step3-title": `記録`,
        "step3-desc": `各種コンプライアンス開示およびカーボンマネジメント要件を満たすデータ形式で構造化データを記録。一貫性とトレーサビリティを確保し、後続の最適化・分析を支援します。`,
        "step4-title": `最適化`,
        "step4-desc": `記録された構造化データをもとに、AI標準化最適化モデルとコンプライアンスルールセットと照合し、エネルギー消費を削減。各種コンプライアンス開示およびカーボンマネジメント要件を満たします。`,
        "cta-title": `この施工現場向けソリューションの活用をご確認ください`,
        "cta-desc": `現場データを接続し、施工プロジェクト全体のエネルギー・材料・カーボン排出の追跡を開始します。`,
        "cta-btn": `デモを依頼`,
      },
    },
    // compliance
    compliance: {
      en: {
        "hero-title": `Consolidate, verify, and manage lifecycle carbon data within standardized LCA assessment and compliance frameworks including MRV and other carbon management requirements`,
        "hero-desc": `Consolidate fragmented data from multiple sources into structured formats, generating standardized lifecycle carbon reports across projects and portfolios — reducing reporting workload by 40–60%. Supporting Scope 1–3 accounting, LCA assessment, MRV, and a broad range of compliance disclosure and carbon management requirements, transforming building data into computable, auditable, and continuously appreciating carbon assets.s and GHG Protocol.`,
        "cap1-title": `Lifecycle Analysis`,
        "cap1-desc": `Calculate carbon emissions across building lifecycle stages A1–C4 using BIM data, standardized LCA models, emission factor databases, and material inputs. Generate corresponding LCA reports.ata derived from BIM models.`,
        "cap2-title": `MRV Monitoring`,
        "cap2-desc": `Generate MRV reports meeting J-credit audit requirements through traceable data lineage and version-controlled methodology libraries, maximizing carbon credit value. outputs.`,
        "cap3-title": `Data Consolidation`,
        "cap3-desc": `Consolidate fragmented data from multiple sources into structured formats, improving reporting efficiency and data asset management — reducing reporting workload by 40–60%. portfolios.`,
        "howto-label": `How it works`,
        "step1-title": `Consolidate`,
        "step1-desc": `Consolidate data from multiple sources including materials, construction, operations, and retrofit into a unified data structure, ensuring the data completeness and consistency required for compliance disclosure and carbon management.e completeness and consistency for lifecycle carbon analysis.`,
        "step2-title": `Calculate`,
        "step2-desc": `Calculate carbon emissions across A1–C4 lifecycle stages using BIM-extracted quantity data combined with other building information and calculation models from methodology libraries, achieving precise and consistent quantification.y data derived from BIM models. Enable accurate and consistent carbon quantification.`,
        "step3-title": `Verify`,
        "step3-desc": `Verify data quality, completeness, and traceability through industry rules, validation logic, and corresponding methodology libraries, ensuring outputs meet audit and compliance requirements.audit-ready outputs aligned with compliance requirements.`,
        "step4-title": `Report`,
        "step4-desc": `Generate structured data outputs and reports meeting various compliance requirements, helping transform building data across projects and portfolios into continuously appreciating carbon assets and maximizing data value. carbon management across projects and portfolios.`,
        "cta-title": `See how this solution applies to your asset management`,
        "cta-desc": `Connect your lifecycle data and start generating auditable carbon reports aligned with compliance and carbon management requirements.`,
        "cta-btn": `Request Demo`,
      },
      jp: {
        "hero-title": `標準化されたLCA評価およびMRVを含む各種コンプライアンス開示・カーボンマネジメント要件のフレームワークに基づき、ライフサイクルカーボンデータを統合・検証・管理します`,
        "hero-desc": `複数ソースの分散データを構造化形式に統合し、プロジェクトおよびポートフォリオ全体の標準化ライフサイクルカーボンレポートを生成。レポート作業量を40〜60%削減します。Scope 1–3算定・LCA評価・MRVおよび各種コンプライアンス開示・カーボンマネジメント要件に対応し、建物データを演算可能・監査対応・継続的に価値を高めるカーボン資産へと転換します。`,
        "cap1-title": `ライフサイクル分析`,
        "cap1-desc": `BIMデータ・標準化LCAモデル・排出係数データベース・材料データをもとに、建物ライフサイクルA1〜C4全段階の炭素排出量を算定。対応するLCAレポートを生成します。`,
        "cap2-title": `MRV監測`,
        "cap2-desc": `追跡可能なデータ系譜とバージョン管理された方法学ライブラリにより、J-creditの監査要件を満たすMRVレポートを生成。カーボンクレジット価値を最大化します。`,
        "cap3-title": `データ統合`,
        "cap3-desc": `複数ソースの分散データを構造化形式に統合し、レポート生成効率とデータ資産管理能力を向上。レポート作業量を40〜60%削減します。`,
        "howto-label": `仕組み`,
        "step1-title": `統合`,
        "step1-desc": `材料・施工・運用・改修など複数ソースのデータを統合し、統一データ構造を構築。各種コンプライアンス開示およびカーボンマネジメント要件に必要なデータの完全性と一貫性を確保します。`,
        "step2-title": `算定`,
        "step2-desc": `BIMから抽出した数量データと他の建物情報および方法学ライブラリの計算モデルを組み合わせ、A1〜C4全段階の炭素排出量を算定。精確かつ一貫した定量化を実現します。`,
        "step3-title": `検証`,
        "step3-desc": `業界ルール・検証ロジック・対応する方法学ライブラリにより、データ品質・完全性・トレーサビリティを検証。出力結果が監査・コンプライアンス要件を満たすことを確保します。`,
        "step4-title": `レポート`,
        "step4-desc": `各種コンプライアンス要件を満たす構造化データ出力とレポートを生成。プロジェクトおよびポートフォリオ全体の建物データを継続的に価値を高めるカーボン資産へと転換し、データ価値を最大化します。`,
        "cta-title": `資産管理における本ソリューションの活用をご確認ください`,
        "cta-desc": `ライフサイクルデータを接続し、コンプライアンスおよびカーボンマネジメント要件に対応した監査可能なカーボンレポートの生成を開始します。`,
        "cta-btn": `デモを依頼`,
      },
    },
    // retrofit
    retrofit: {
      en: {
        "hero-title": `Plan, evaluate, and execute circular retrofit and deconstruction scenarios driven by data, AI standardized models, and rule sets for asset reuse and material recovery`,
        "hero-desc": `Establish asset inventories through 3D scanning and BIM digitization, make decisions based on lifecycle and material recovery data, plan and execute optimal retrofit or deconstruction scenarios, identify reusable assets, and classify materials — reducing construction waste by 30–50% and improving building circularity.rove material recovery rates.`,
        "cap1-title": `Pre-Deconstruction Audit`,
        "cap1-desc": `Digitize buildings and assets through scanning technologies and BIM modeling to generate structured data inventories containing geometry, material, and condition information — forming a building resource deconstruction record and conducting asset circularity assessments based on AI standardized models and circular strategy rule sets. attributes.`,
        "cap2-title": `Circularity Assessment`,
        "cap2-desc": `Based on audit results, combined with recoverability, residual value, and circular strategy rule sets, propose retrofit or deconstruction scenarios that maximize circularity.d criteria.`,
        "cap3-title": `Waste Tracking`,
        "cap3-desc": `Manage and track post-deconstruction material quantities and disposal destinations through structured logging mechanisms, ensuring compliance and traceability of deconstructed material data.eporting.`,
        "howto-label": `How it works`,
        "step1-title": `Scan`,
        "step1-desc": `Scan buildings and assets to capture geometric, material, and condition data, generating BIM-aligned digital asset inventories and establishing a structured data foundation for subsequent pre-deconstruction audit.gital asset representations. Create structured datasets for existing buildings to support downstream analysis.`,
        "step2-title": `Pre-Deconstruction Audit`,
        "step2-desc": `Audit asset condition, material composition, and reuse potential based on AI standardized models and circular strategy rule sets, identifying component recoverability and evaluating disposal options.ntify reusable components and assess recovery potential.`,
        "step3-title": `Circularity Assessment`,
        "step3-desc": `Based on audit results, combined with recoverability, residual value, and circular strategy rule sets, propose retrofit or deconstruction scenarios that maximize circularity — providing visual data presentation as a standardized basis for execution. decision inputs for retrofit and recovery planning.`,
        "step4-title": `Execute &amp; Track`,
        "step4-desc": `Execute retrofit and recovery strategies based on the planned scenarios, manage and track post-deconstruction material quantities and disposal destinations, ensure material data compliance and traceability, and improve material recovery and reuse rates while reducing waste.overy rates and reduce waste across projects.`,
        "cta-title": `See how this solution applies to your deconstruction or retrofit projects`,
        "cta-desc": `Connect your asset data and start planning circular retrofit and deconstruction strategies.`,
        "cta-btn": `Request Demo`,
      },
      jp: {
        "hero-title": `データ・AI標準化モデル・ルールセットに基づく資産再利用とマテリアルリカバリー分析により、循環型改修・解体シナリオを立案・評価・実行します`,
        "hero-desc": `3DスキャニングとBIMデジタル化により資産インベントリを構築し、ライフサイクルおよびマテリアルリカバリーデータに基づいて意思決定。最適な改修・解体シナリオを立案・実行し、再利用可能な資産を特定・材料を分類することで、建設廃棄物を30〜50%削減し建物の循環性を向上させます。`,
        "cap1-title": `解体前審査`,
        "cap1-desc": `スキャン技術とBIMモデリングにより建物・資産をデジタル化し、形状・材料・状態情報を含む構造化データインベントリを生成。建物リソース解体記録を形成し、AI標準化モデルと循環型戦略ルールセットに基づく資産サーキュラリティ評価を実施します。`,
        "cap2-title": `サーキュラリティ評価`,
        "cap2-desc": `審査結果をもとに、回収可能性・残存価値・循環型戦略ルールセットと組み合わせ、循環性を最大化する改修・解体シナリオを提案します。`,
        "cap3-title": `廃棄物追跡`,
        "cap3-desc": `記録メカニズムにより、解体後の材料数量と処分先を管理・追跡。解体材料データのコンプライアンスとトレーサビリティを確保します。`,
        "howto-label": `仕組み`,
        "step1-title": `スキャン`,
        "step1-desc": `建物と資産をスキャンし、形状・材料・状態データを取得。BIM整合型デジタル資産インベントリを生成し、後続の解体前審査に向けた構造化データ基盤を構築します。`,
        "step2-title": `解体前審査`,
        "step2-desc": `AI標準化モデルと循環型戦略ルールセットに基づき、資産状態・材料構成・再利用ポテンシャルを審査。構成部材の回収可能性を特定し、処分方法を評価します。`,
        "step3-title": `サーキュラリティ評価`,
        "step3-desc": `審査結果をもとに、回収可能性・残存価値・循環型戦略ルールセットと組み合わせ、循環性を最大化する改修・解体シナリオを提案。可視化データを提供し、実行のための標準化された根拠とします。`,
        "step4-title": `実行・追跡`,
        "step4-desc": `策定した改修・解体シナリオに基づき、改修・回収戦略を実行。解体後の材料数量と処分先を管理・追跡し、材料データのコンプライアンスとトレーサビリティを確保。材料回収率と再利用率を向上させ、廃棄物を削減します。`,
        "cta-title": `解体・改修プロジェクトにおける本ソリューションの活用をご確認ください`,
        "cta-desc": `資産データを接続し、循環型改修・解体戦略の立案を開始します。`,
        "cta-btn": `デモを依頼`,
      },
    },
    // materials
    materials: {
      en: {
        "hero-title": `Explore and compare low-carbon materials and reusable components to support more efficient design and procurement decisions`,
        "hero-desc": `Based on material reuse and EPD records, access EPD data, supplier information, and inventory data to explore low-carbon materials and reusable components — improving design and procurement decision-making efficiency and helping reduce embodied carbon by 10–25%.nt transparency.`,
        "cap1-title": `Material Data`,
        "cap1-desc": `Access EPDs, technical specifications, carbon intensity data, and compliance attributes across material categories and suppliers, supporting standardized material decision-making.rement decisions.`,
        "cap2-title": `Reuse Inventory`,
        "cap2-desc": `Browse reusable material and component inventories with metadata on condition, quantity, location, and availability — quickly identifying available resources.`,
        "cap3-title": `Material Selection Efficiency`,
        "cap3-desc": `Improve material selection efficiency through structured data comparison and multi-dimensional filtering, reducing decision costs in design and procurement, and helping reduce embodied carbon by 10–25%.`,
        "howto-label": `How it works`,
        "step1-title": `Search`,
        "step1-desc": `Search supplier networks for low-carbon material data and reuse inventory, accessing structured information including EPDs, technical specifications, and stock availability.ding EPDs, specifications, and availability.`,
        "step2-title": `Select`,
        "step2-desc": `Filter candidate materials based on performance, carbon intensity, and compliance requirements, supporting multi-attribute and combined-condition filtering and matching. using structured attributes and multi-criteria conditions.`,
        "step3-title": `Shortlist`,
        "step3-desc": `Save and organize filtered results into candidate material shortlists, supporting cross-project material comparison and option management. comparison and tracking of preferred options across projects.`,
        "step4-title": `Evaluate`,
        "step4-desc": `Improve decision-making efficiency in material evaluation and multi-option comparison based on lifecycle impact, technical parameters, and supply constraints.son and data-driven decision-making across alternatives.`,
        "cta-title": `See how this solution applies to your material sourcing`,
        "cta-desc": `Connect your material data and start exploring low-carbon and reusable options for your projects.`,
        "cta-btn": `Explore`,
      },
      jp: {
        "hero-title": `低炭素材料と再利用可能な構成部材を探索・比較し、より効率的な設計・調達の意思決定を支援します`,
        "hero-desc": `材料再利用・EPDアーカイブをもとに、EPDデータ・サプライヤー情報・在庫データにアクセス。低炭素材料と再利用可能な構成部材を探索し、設計・調達の意思決定効率を向上。隠れたカーボン排出を10〜25%削減することに貢献します。`,
        "cap1-title": `材料データ`,
        "cap1-desc": `各材料カテゴリとサプライヤーにわたるEPD・技術仕様・炭素強度・コンプライアンス属性データにアクセス。標準化された材料意思決定を支援します。`,
        "cap2-title": `再利用在庫`,
        "cap2-desc": `状態・数量・位置・在庫状況のメタデータを含む再利用材料・構成部材のインベントリを閲覧。利用可能なリソースを迅速に特定します。`,
        "cap3-title": `材料選定効率化`,
        "cap3-desc": `構造化データ比較と多次元フィルタリングにより材料選定効率を向上。設計・調達フェーズの意思決定コストを削減し、隠れたカーボン排出を10〜25%削減することに貢献します。`,
        "howto-label": `仕組み`,
        "step1-title": `検索`,
        "step1-desc": `サプライヤーネットワークから低炭素材料データと再利用在庫を検索。EPD・技術仕様・在庫状況などの構造化情報を取得します。`,
        "step2-title": `選定`,
        "step2-desc": `性能・炭素強度・コンプライアンス要件に基づいて候補材料をフィルタリング。多次元属性と組み合わせ条件によるフィルタリング・マッチングを支援します。`,
        "step3-title": `保存`,
        "step3-desc": `フィルタリング結果を候補材料リストとして保存・整理。プロジェクトをまたいだ材料比較とオプション管理を支援します。`,
        "step4-title": `評価`,
        "step4-desc": `ライフサイクル影響・技術パラメーター・供給制約に基づき、材料評価と複数案比較における意思決定効率を向上させます。`,
        "cta-title": `材料調達における本ソリューションの活用をご確認ください`,
        "cta-desc": `材料データを接続し、プロジェクトの低炭素・再利用可能な選択肢の探索を開始します。`,
        "cta-btn": `詳しく見る`,
      },
    },
  },
};

// Export for module environments (optional)
if (typeof module !== "undefined") module.exports = COPY;